# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

title: "Alex Shonenkov"
locale: "en-US"
title_separator: ""
subtitle: "Data Scientist"
name: "Alex Shonenkov"
description: "Personal blog of Data Scientist (NLP, CV, ML, TS) Alex Shonenkov."
url: "https://shonenkov.github.io"
baseurl: ""
repository: "shonenkov/shonenkov.github.io"
logo: "/assets/images/gm.png"
breadcrumbs: true
words_per_minute: 200
search: false
paginate: 5
timezone: UTC

layout: single
classes:
  - landing
  - dark-theme

excerpt: "This post should display a **header with a solid background color**, if the theme supports it."
header:
  teaser: "/assets/images/mm-teaser-images-example.jpg"

#excerpt: "This post should display a **header with an overlay image**, if the theme supports it."
#header:
#  image: "/assets/images/mm-teaser-images-example.jpg"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      comments: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/shonenkov"
    - "https://www.facebook.com/shonenkov"
    - "https://instagram.com/shonenkov"
    - "https://www.linkedin.com/in/shonenkov"

author:
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "My awesome biography **constrained** to a sentence or two goes here."
  location : "Russia, Adler"
  facebook : "shonenkov"
  kaggle   : "shonenkov"
  employer         :
  pubmed           :
  googlescholar    :
  email            : "shonenkov@phystech.edu"
  researchgate     :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  foursquare       :
  github           : "shonenkov"
  google_plus      :
  keybase          :
  instagram        : "shonenkov"
  impactstory      :
  lastfm           :
  linkedin         : "shonenkov"
  orcid            :
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          : "shonenkov"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :



# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# SEO Related
google_site_verification : "rDlkvdAlNVIvPQCgepa5zIjn5KyhB2rYIukO-rp-7Zs"
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Analytics
analytics:
  provider               :  "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-172113653-1"